
USE ROLE ACCOUNTADMIN;

-- Compute: extra-small, auto-suspend fast so the trial credits last.
CREATE WAREHOUSE IF NOT EXISTS FD_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND   = 60
  AUTO_RESUME    = TRUE
  INITIALLY_SUSPENDED = TRUE;

-- Database + medallion schemas.
CREATE DATABASE IF NOT EXISTS FOOD_DELIVERY;

-- Bronze: raw/source data
CREATE SCHEMA IF NOT EXISTS FOOD_DELIVERY.BRONZE;

-- Raw: fallback COPY INTO ingestion layer
CREATE SCHEMA IF NOT EXISTS FOOD_DELIVERY.RAW;

-- Silver: cleaned and conformed data
CREATE SCHEMA IF NOT EXISTS FOOD_DELIVERY.STAGING;

-- Gold: business-ready analytics
CREATE SCHEMA IF NOT EXISTS FOOD_DELIVERY.MARTS;

-- Historical / SCD Type 2 data
CREATE SCHEMA IF NOT EXISTS FOOD_DELIVERY.SNAPSHOTS;

-- AI-generated / LLM-enriched data
CREATE SCHEMA IF NOT EXISTS FOOD_DELIVERY.AI;


-- A role dbt/Airflow will use.
CREATE ROLE IF NOT EXISTS DBT_ROLE;

-- Warehouse permissions
GRANT USAGE
ON WAREHOUSE FD_WH
TO ROLE DBT_ROLE;

GRANT OPERATE
ON WAREHOUSE FD_WH
TO ROLE DBT_ROLE;

-- Database permissions
GRANT ALL
ON DATABASE FOOD_DELIVERY
TO ROLE DBT_ROLE;

-- Existing schemas
GRANT ALL
ON ALL SCHEMAS IN DATABASE FOOD_DELIVERY
TO ROLE DBT_ROLE;

-- Future schemas
GRANT ALL
ON FUTURE SCHEMAS IN DATABASE FOOD_DELIVERY
TO ROLE DBT_ROLE;

-- Existing tables
GRANT ALL
ON ALL TABLES IN DATABASE FOOD_DELIVERY
TO ROLE DBT_ROLE;

-- Future tables
GRANT ALL
ON FUTURE TABLES IN DATABASE FOOD_DELIVERY
TO ROLE DBT_ROLE;

-- Existing views
GRANT ALL
ON ALL VIEWS IN DATABASE FOOD_DELIVERY
TO ROLE DBT_ROLE;

-- Future views
GRANT ALL
ON FUTURE VIEWS IN DATABASE FOOD_DELIVERY
TO ROLE DBT_ROLE;

-- Let your login use the role (replace with your Snowflake username).
SET my_user = CURRENT_USER();
GRANT ROLE DBT_ROLE TO USER IDENTIFIER($my_user);

SELECT 'setup complete' AS status;