# Name your project! Project names should contain only lowercase characters
# and underscores.
name: "food_delivery_dbt"
version: "1.0.0"

# Profile used by this dbt project.
profile: "food_delivery_dbt"

# Project directories.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Directories removed by `dbt clean`.
clean-targets:
  - "target"
  - "dbt_packages"

# Model configurations.
models:
  food_delivery_dbt:

    # Staging models are created as views.
    staging:
      +materialized: view
      +schema: staging

    # Mart models are created as tables.
    marts:
      +materialized: table
      +schema: marts